### ISSUE TITLE
feat: 'registry-url' input option

### ISSUE THREAD

**Issue by dai-shi** [DerYeger/pnpm-setup-action#1]
### Affected Packages

- [ ] @yeger/eslint-config
- [ ] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

Hi, is it possible to pass `registry-url` so that it configures authentication?
https://github.com/actions/setup-node/blob/64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c/src/main.ts#L58-L60

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
I think this can be configured using an `.npmrc` file, as described in the [pnpm docs](https://pnpm.io/npmrc#registry--authentication-settings).

**Comment by dai-shi** [comment]
Thanks. For my use case, I don't need to change the url from the default one. I just noticed that, without it, `setup-node` doesn't configure `NPM_CONFIG_USERCONFIG` env var, which my workflow uses.

So, what I wanted is simply to pass through `registory-url` along with `node-version`.

**Comment by DerYeger** [comment]
I see. I had a look at the source of `setup-node`.
So providing this input results in the following line setting this env variable.

https://github.com/actions/setup-node/blob/ae9f0f7448e93b1be0f44663e79763dbdffcc4da/src/authutil.ts#L53

However, this can trivially be set manually as well, using, e.g., either `$HOME/.npmrc` or `./.npmrc`.
See https://docs.npmjs.com/cli/v6/using-npm/config#npmrc-files.

I don't think it's necessary to provide a dummy input for this opinionated action just to set an env variable.

**Comment by dai-shi** [comment]
Hmm, I might be missing something but specifying `repository-url` is pretty common.
As I'm following this doc: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry

```yaml
name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

Maybe, there's a pnpm way of doing this `NPM_TOKEN` thing, with which I can migrate.

**Comment by DerYeger** [comment]
Ye, it's common. But IMO it's better to handle it via an `.npmrc` to have a single source of truth.

I'm confused about your requirements.

The following publish snippet is not connected at all to the `setup-node` step.

```yml
- run: npm publish
  env:
     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

How is this related to `NPM_CONFIG_USERCONFIG`?
